### ISSUE TITLE
align images on gemeentegeschiedenis with actual changes in municipality borders

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/wp2-GISLOD#1]
Municipalities on gemeentegeschiedenis.nl are depicted for each year that the municipality experienced a border change. However from 1998 onwards, there various depictions, but this is related to different use of sources to draw the polygons from.

**Comment by emacgillavry** [comment]
We now check for significant changes of the border only. If there is less than 1% of change with respect to the previous year, the change will not be incorporated.
