### ISSUE TITLE
Wijzigingen gemeentegrenzen volledig?

### ISSUE THREAD

**Issue by hekl** [CLARIAH/wp2-GISLOD#12]
In 1896 werd Amsterdam uitgebreid met delen van Diemen, Nieuwer-Amstel en Sloten. Onno vermeldt dit ook op pagina 6 in de tekst van het repertorium, maar in de beschrijvingen van wijzigingen van gemeenten wordt deze grenswijziging niet vermeld bij Amsterdam of de andere gemeenten. Er is ook geen shape van. Ik heb er zelf wel een gemaakt voor mijn website. Dit doet de vraag rijzen: hoe volledig is het Reportorium en gemeentegeschiedenis.nl?

**Comment by emacgillavry** [comment]
Er zijn geen grenswijzigingen opgenomen, enkel gemeenten die zijn samengevoegd of opgesplitst of hernoemd.
