### ISSUE TITLE
Doniawerstal has no map

### ISSUE THREAD

**Issue by ivozandhuis** [CLARIAH/wp2-GISLOD#13]
http://www.gemeentegeschiedenis.nl/gemeentenaam/Doniawerstal

**Comment by emacgillavry** [comment]
Doniawerstal has a map now: 
![doniawerstal](https://cloud.githubusercontent.com/assets/1555712/24866887/d30d68a4-1e0b-11e7-9539-e8fbeb36a43b.png)
