### ISSUE TITLE
'new' municipalities not available in search of gemeentegeschiedenis

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/wp2-GISLOD#2]
'new' municipalities not available in search of gemeentegeschiedenis, however they are available via the 2016 map, e.g.:

Nissewaard: http://www.gemeentegeschiedenis.nl/amco/10735
Fryske Marren: http://www.gemeentegeschiedenis.nl/amco/10022

**Comment by ivozandhuis** [comment]
This is because we use the histopo API for searching?

**Comment by emacgillavry** [comment]
For example, one can now search for [Meierijstad](http://www.gemeentegeschiedenis.nl/gemeentenaam/Meierijstad) and all other new municipalities since 1997 until now that we're not available previously.
